trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install and build'
  
- task: Docker@2
  inputs:
    containerRegistry: 'KjipestDockerRegistry'
    repository: 'KjipestNodeServer'
    command: 'build'
    Dockerfile: '**/server/Dockerfile'
  displayName: 'Docker image build'

- task: Docker@2
  inputs:
    containerRegistry: 'KjipestDockerRegistry'
    repository: 'KjipestNodeServer'
    command: 'push'
  displayName: 'Docker image push'